font_base_directory: "{{ home_dir }}/.fonts"

font_families:
  - Iosevka:nerd
  - Patrick Hand:google
  - Recursive:google
  - Recursive Mono Casual:google
  - Roboto:google
  - Tangerine:google
  - Nunito Sans:google
  - Noto Music:google
  - Source Code Pro:google
  - Space Mono:google
  - Hack:nerd
  - NerdFontsSymbolsOnly:nerd
#  - FiraMono
