import click

from infra.tools.ghsync.utils.db import TABLE_DEFINITIONS


def _map_sql_type_to_lisp(col_def):
    col_def = col_def.upper()
    lisp_type = "any"
    if "INTEGER" in col_def:
        lisp_type = "integer"
    elif "TEXT" in col_def:
        lisp_type = "string"

    if "NOT NULL" not in col_def:
        lisp_type += " or nil"

    return lisp_type


def _singularize(table_name):
    if table_name.endswith("ies"):
        return table_name[:-3] + "y"
    if table_name.endswith("s"):
        return table_name[:-1]
    return table_name


@click.command()
@click.option(
    "--output",
    type=click.File("w"),
    default="-",
    help="Output file for the models. Defaults to stdout.",
)
def model(output):
    """Outputs CL structs for database tables."""
    comment = """;;; -*- lexical-binding: t -*-
;;;
;;; This file is automatically generated. DO NOT EDIT.
;;;
;;; To regenerate, run:
;;;   bazel run infra/tools/ghsync:main -- model --output <path-to-this-file>
"""
    print(comment, file=output)

    first_table = True
    for table_name, definition in TABLE_DEFINITIONS.items():
        if not first_table:
            print("\n", file=output)
        first_table = False

        singular_name = _singularize(table_name)
        struct_name = f"neo-{singular_name.replace('_', '-')}"
        print(f"(cl-defstruct {struct_name}", file=output)

        columns = definition["columns"]
        if not columns:
            print(")", file=output)
            continue

        lisp_columns = [col_name.replace("_", "-") for col_name, _ in columns]
        max_len = max(len(name) for name in lisp_columns)

        for i, (col_name, col_type) in enumerate(columns):
            lisp_col_name = lisp_columns[i]
            lisp_type_comment = _map_sql_type_to_lisp(col_type)

            field_def = lisp_col_name
            if i == len(columns) - 1:
                field_def += ")"

            padded_def = f"{field_def:<{max_len + 3}}"
            print(f"  {padded_def};; {lisp_type_comment}", file=output)
